import { sql } from "drizzle-orm";
import { check, index, integer, sqliteTable, text, unique } from "drizzle-orm/sqlite-core";
import { entityStatuses, entityTypes } from "@module-atelier/contracts";

/**
 * A project database (BE-003): one file per project, holding that project's
 * content and revision history.
 *
 * Consequences of the per-project file boundary:
 * - Cross-project integrity is structural. A relation cannot reference another
 *   project's entity because that entity lives in a different database file, so
 *   the composite foreign keys of the PostgreSQL design are gone.
 * - `project_id` is still stored and enforced with a foreign key to the single
 *   `projects` row in this file, because the contract's payloads carry it.
 *
 * PostgreSQL features map to SQLite as follows:
 * - `uuid` -> TEXT holding a UUID string, generated by the application.
 * - `timestamptz` -> INTEGER epoch milliseconds, UTC by construction.
 * - `jsonb` -> TEXT guarded by `json_valid()` and `json_type()` checks.
 * - `text[]` -> TEXT holding a JSON array with a type check.
 * - enums -> TEXT with a CHECK, which is easier to evolve than a type.
 */

const uuid = (name: string) => text(name);
const id = () => text("id").primaryKey().$defaultFn(() => crypto.randomUUID());
const createdAt = () => integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date());
const updatedAt = () => integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date());

const jsonList = (values: readonly string[]) =>
  sql.raw(values.map((value) => `'${value.replace(/'/g, "''")}'`).join(", "));

export const projects = sqliteTable(
  "projects",
  {
    id: id(),
    name: text("name").notNull(),
    /** Presentation and publishing preferences; never layout semantics. */
    settings: text("settings").notNull().default("{}"),
    schemaVersion: integer("schema_version").notNull().default(1),
    createdAt: createdAt(),
    updatedAt: updatedAt()
  },
  (table) => [check("projects_settings_object", sql`json_valid(${table.settings}) and json_type(${table.settings}) = 'object'`)]
);

export const documents = sqliteTable(
  "documents",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    title: text("title").notNull(),
    /** Markdown source is authoritative; rendered HTML is never stored. */
    content: text("content").notNull().default(""),
    revision: integer("revision").notNull().default(1),
    createdAt: createdAt(),
    updatedAt: updatedAt()
  },
  (table) => [
    index("documents_created_idx").on(table.createdAt, table.id),
    check("documents_revision_positive", sql`${table.revision} > 0`)
  ]
);

export const entities = sqliteTable(
  "entities",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    name: text("name").notNull(),
    /** JSON array of strings. */
    aliases: text("aliases").notNull().default("[]"),
    description: text("description").notNull().default(""),
    structuredData: text("structured_data").notNull().default("{}"),
    status: text("status").notNull().default("draft"),
    revision: integer("revision").notNull().default(1),
    createdAt: createdAt(),
    updatedAt: updatedAt()
  },
  (table) => [
    index("entities_created_idx").on(table.createdAt, table.id),
    index("entities_type_idx").on(table.type),
    check("entities_type_valid", sql`${table.type} in (${jsonList(entityTypes)})`),
    check("entities_status_valid", sql`${table.status} in (${jsonList(entityStatuses)})`),
    check("entities_aliases_array", sql`json_valid(${table.aliases}) and json_type(${table.aliases}) = 'array'`),
    check(
      "entities_structured_data_object",
      sql`json_valid(${table.structuredData}) and json_type(${table.structuredData}) = 'object'`
    ),
    check("entities_revision_positive", sql`${table.revision} > 0`)
  ]
);

export const relations = sqliteTable(
  "relations",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    fromEntityId: uuid("from_entity_id")
      .notNull()
      .references(() => entities.id, { onDelete: "cascade" }),
    toEntityId: uuid("to_entity_id")
      .notNull()
      .references(() => entities.id, { onDelete: "cascade" }),
    type: text("type").notNull(),
    metadata: text("metadata"),
    createdAt: createdAt(),
    updatedAt: updatedAt()
  },
  (table) => [
    unique("relations_edge_unique").on(table.projectId, table.fromEntityId, table.type, table.toEntityId),
    index("relations_from_idx").on(table.fromEntityId),
    index("relations_to_idx").on(table.toEntityId),
    check("relations_metadata_object", sql`${table.metadata} is null or (json_valid(${table.metadata}) and json_type(${table.metadata}) = 'object')`)
  ]
);

export const revisions = sqliteTable(
  "revisions",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    resourceType: text("resource_type").notNull(),
    /** Deliberately not a foreign key: history outlives the resource it describes. */
    resourceId: uuid("resource_id").notNull(),
    revision: integer("revision").notNull(),
    baseRevision: integer("base_revision").notNull(),
    authorId: text("author_id").notNull(),
    /** Full state after this revision; internal, never returned by the API. */
    snapshot: text("snapshot").notNull(),
    createdAt: createdAt()
  },
  (table) => [
    unique("revisions_resource_revision_unique").on(table.resourceType, table.resourceId, table.revision),
    index("revisions_resource_history_idx").on(table.resourceType, table.resourceId, table.revision),
    check("revisions_resource_type_valid", sql`${table.resourceType} in ('document', 'entity')`),
    check("revisions_revision_positive", sql`${table.revision} > 0`),
    check("revisions_base_revision_nonnegative", sql`${table.baseRevision} >= 0`),
    check("revisions_snapshot_object", sql`json_valid(${table.snapshot}) and json_type(${table.snapshot}) = 'object'`)
  ]
);

export type ProjectRowSqlite = typeof projects.$inferSelect;
export type DocumentRowSqlite = typeof documents.$inferSelect;
export type EntityRowSqlite = typeof entities.$inferSelect;
export type RelationRowSqlite = typeof relations.$inferSelect;
export type RevisionRowSqlite = typeof revisions.$inferSelect;